var GggObjectManager = require("./GggObjectManager");
console.log("\n objectAssignSample: ");
GggObjectManager.objectAssignSample();
console.log("\n deepCloneSample: ");
GggObjectManager.deepCloneSample();
console.log("\n mergingObjectsSample: ");
GggObjectManager.mergingObjectsSample();
console.log("\n mergingObjectsWithSamePropertiesSample: ");
GggObjectManager.mergingObjectsWithSamePropertiesSample();
console.log("\n completeAssign: ");
var obj = GggObjectManager.getObjectSample();
var copy = GggObjectManager.completeAssign({}, obj);
console.log(copy);
console.log(copy.bar);
console.log("\n initializeVariableSample: ");
GggObjectManager.initializeVariableSample();
console.log("\n initializeArraySample: ");
GggObjectManager.initializeArraySample();
console.log("\n spreadOperatorSample: ");
GggObjectManager.spreadOperatorSample();
